apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kafkatopics.kafkaopscontroller.mattfanto.github.com
spec:
  group: kafkaopscontroller.mattfanto.github.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                topicName:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                partitions:
                  type: integer
                  minimum: 1
            status:
              type: object
              properties:
                statusCode:
                  type: string
                replicas:
                  type: integer
                partitions:
                  type: integer
                conditions:
                  description: List of status conditions to indicate the status of a
                    kafka topic compared to the specification above.
                  items:
                    description: All status condition information
                    properties:
                      lastTransitionTime:
                        description: LastTransitionTime is the timestamp corresponding
                          to the last status change of this condition.
                        format: date-time
                        type: string
                      message:
                        description: Message is a human readable description of the
                          details of the last transition, complementing reason.
                        type: string
                      reason:
                        description: Reason is a brief machine readable explanation
                          for the condition's last transition.
                        type: string
                      status:
                        description: Status of the condition, one of (`True`, `False`,
                          `Unknown`).
                        enum:
                          - "True"
                          - "False"
                          - Unknown
                        type: string
                      type:
                        description: Type of the condition, known values are (`Ready`,
                          `InvalidRequest`).
                        type: string
                    required:
                      - status
                      - type
                    type: object
                  type: array
  names:
    kind: KafkaTopic
    plural: kafkatopics
  scope: Namespaced
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kafkaops-controller-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kafkaops-controller-manager-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kafkaops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkaops-controller-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  #  - apiGroups:
  #      - ""
  #    resources:
  #      - secrets
  #    verbs:
  #      - create
  #      - delete
  #      - get
  #      - list
  #      - patch
  #      - update
  #      - watch
  - apiGroups:
      - kafkaopscontroller.mattfanto.github.com
    resources:
      - kafkatopics
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaops-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - image: ghcr.io/mattfanto/kafkaops-controller:0.1-snapshot
          imagePullPolicy: IfNotPresent
          name: kafkaops-controller
          args:
            - -bootstrap-servers=kafka-0.kafka-headless.kafkaops.svc.cluster.local:9092
          command:
            - /kafkaops-controller
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10