apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaops-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - image: ghcr.io/mattfanto/kafkaops-controller:0.1-snapshot
          imagePullPolicy: IfNotPresent
          name: kafkaops-controller
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10