apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kafkaops-controller-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kafkaops-controller-manager-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kafkaops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkaops-controller-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
#  - apiGroups:
#      - ""
#    resources:
#      - secrets
#    verbs:
#      - create
#      - delete
#      - get
#      - list
#      - patch
#      - update
#      - watch
  - apiGroups:
      - kafkaopscontroller.mattfanto.github.com
    resources:
      - kafkatopics
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch